WITH SUBORD(manager_id, subord_id) AS
  (SELECT  MANAGER_ID, EMPLOYEE_ID 
  FROM EMPLOYEES
  UNION ALL
  SELECT E.MANAGER_ID,SUBORD.SUBORD_ID 
  FROM EMPLOYEES e, SUBORD 
  WHERE e.EMPLOYEE_ID=SUBORD.MANAGER_ID)
SELECT REGION_NAME
FROM REGIONS
JOIN COUNTRIES 
ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
JOIN LOCATIONS 
ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
JOIN DEPARTMENTS 
ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
JOIN 
(SELECT manager_id
FROM
(
SELECT manager_id,
 CNT, 
 DENSE_RANK() OVER(ORDER BY CNT DESC) AS DR
FROM
(
SELECT manager_id,COUNT(1) AS CNT
FROM SUBORD 
WHERE manager_ID IS NOT NULL
GROUP BY manager_id
) SUBORD_COUNT
) SUBORD_RANKED
WHERE DR = 1
) MOST_SUBORD
ON MOST_SUBORD.manager_id = DEPARTMENTS.MANAGER_ID
;